#!/usr/bin/env python3
"""Regenerate sitemap.xml from scratch, crawling all index.html files."""

import os
import json
from datetime import date, datetime

BASE    = os.path.dirname(os.path.abspath(__file__))
DOMAIN  = 'https://sifufinds.com'
TODAY   = date.today().isoformat()


def file_lastmod(url: str) -> str:
    """Return the ISO date of the index.html for this URL, falling back to TODAY."""
    path = url.replace(DOMAIN, '').strip('/')
    candidates = [
        os.path.join(BASE, path, 'index.html'),
        os.path.join(BASE, path + '.html'),
    ]
    for fp in candidates:
        if os.path.exists(fp):
            return datetime.fromtimestamp(os.path.getmtime(fp)).strftime('%Y-%m-%d')
    return TODAY

# Directories to exclude from crawl
EXCLUDED_DIRS = {
    'agents', 'firecrawl', 'geo-content-writer', 'supabase',
    '.git', '.github', '.venv', '__pycache__', 'node_modules',
    '.claude', 'data',
}

# Priority and changefreq by URL pattern
def classify(url: str):
    path = url.replace(DOMAIN, '').strip('/')

    if path == '':
        return '1.0', 'daily'
    if path in ('tips', 'tips/', 'casino', 'casino/', 'odds', 'odds/', 'blog', 'blog/'):
        return '0.9', 'hourly'
    if path.startswith('tips/world-cup-2026'):
        return '0.9', 'daily'
    if path.startswith('blog/') and path.count('/') == 1:
        return '0.8', 'weekly'
    if path.startswith('countries/') and path.count('/') == 1:
        return '0.9', 'daily'
    if path.startswith('countries/') and path.count('/') == 2:
        # city page
        return '0.75', 'weekly'
    if path.startswith('bookmakers/') and path.count('/') == 1:
        # main bookmaker review
        return '0.85', 'weekly'
    if path.startswith('bookmakers/') and path.count('/') == 2:
        # bookmaker × country
        return '0.8', 'weekly'
    if path.startswith('betting/') and path.count('/') == 1:
        # payment method hub
        return '0.8', 'weekly'
    if path.startswith('betting/') and path.count('/') == 2:
        # payment × country or sport × country
        return '0.75', 'weekly'
    if path.startswith('guides/'):
        return '0.7', 'monthly'
    if path.startswith('bonuses/'):
        return '0.75', 'weekly'
    if path.startswith('casino/') or path.startswith('odds/'):
        return '0.7', 'daily'
    if path.startswith('about') or path.startswith('contact'):
        return '0.4', 'monthly'

    return '0.6', 'monthly'


def collect_urls():
    urls = []
    for root, dirs, files in os.walk(BASE):
        # Prune excluded directories in-place
        dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS and not d.startswith('.')]

        if 'index.html' not in files:
            continue

        rel = os.path.relpath(root, BASE)
        if rel == '.':
            url = f'{DOMAIN}/'
        else:
            rel_norm = rel.replace(os.sep, '/')
            url = f'{DOMAIN}/{rel_norm}/'

        # Skip analytics, google verification pages
        if any(skip in url for skip in ['/analytics', '/google3', '/gen_', '/.', '/data/']):
            continue

        urls.append(url)

    return sorted(set(urls))


CHILD_SITEMAPS = [
    ('sitemap-core.xml',       lambda p: p in ('', 'tips', 'casino', 'odds', 'blog', 'countries',
                                                'bookmakers', 'betting', 'guides', 'bonuses',
                                                'about', 'contact')),
    ('sitemap-countries.xml',  lambda p: p.startswith('countries/')),
    ('sitemap-blog.xml',       lambda p: p.startswith('blog/') and p != 'blog'),
    ('sitemap-tips.xml',       lambda p: p.startswith('tips/')),
    ('sitemap-betting.xml',    lambda p: p.startswith('betting/') or p.startswith('bookmakers/')),
    ('sitemap-guides.xml',     lambda p: p.startswith('guides/') or p.startswith('bonuses/') or
                                         p.startswith('casino/')),
]


def _url_block(url: str) -> list[str]:
    priority, changefreq = classify(url)
    lastmod = file_lastmod(url)
    return [
        '  <url>',
        f'    <loc>{url}</loc>',
        f'    <lastmod>{lastmod}</lastmod>',
        f'    <changefreq>{changefreq}</changefreq>',
        f'    <priority>{priority}</priority>',
        '  </url>',
    ]


def build_child_sitemap(name: str, urls: list[str]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
        '',
        f'  <!-- {name} — auto-generated by gen_sitemap.py — {TODAY} — {len(urls)} URLs -->',
        '',
    ]
    for url in sorted(urls):
        lines.extend(_url_block(url))
    lines.append('</urlset>')
    return '\n'.join(lines)


def build_sitemap_index(child_names: list[str]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        '',
        f'  <!-- Sitemap index — auto-generated by gen_sitemap.py — {TODAY} -->',
        '',
    ]
    for name in child_names:
        lines += [
            '  <sitemap>',
            f'    <loc>{DOMAIN}/{name}</loc>',
            f'    <lastmod>{TODAY}</lastmod>',
            '  </sitemap>',
        ]
    lines.append('</sitemapindex>')
    return '\n'.join(lines)


def main():
    urls = collect_urls()
    print(f'  Found {len(urls)} indexable URLs')

    # Assign each URL to its child sitemap bucket
    buckets: dict[str, list[str]] = {name: [] for name, _ in CHILD_SITEMAPS}
    overflow: list[str] = []
    for url in urls:
        path = url.replace(DOMAIN, '').strip('/')
        assigned = False
        for name, pred in CHILD_SITEMAPS:
            if pred(path):
                buckets[name].append(url)
                assigned = True
                break
        if not assigned:
            overflow.append(url)

    if overflow:
        buckets.setdefault('sitemap-other.xml', []).extend(overflow)

    # Write child sitemaps
    written_names = []
    for name, urls_in_bucket in buckets.items():
        if not urls_in_bucket:
            continue
        content = build_child_sitemap(name, urls_in_bucket)
        out_path = os.path.join(BASE, name)
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(content)
        written_names.append(name)
        print(f'  ✓  {name} — {len(urls_in_bucket)} URLs')

    # Write sitemap index
    index_content = build_sitemap_index(written_names)
    index_path = os.path.join(BASE, 'sitemap.xml')
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(index_content)
    print(f'  ✓  sitemap.xml (index) — {len(written_names)} child sitemaps, {len(urls)} total URLs')


if __name__ == '__main__':
    main()
