#!/usr/bin/env python3
"""Regenerate sitemap.xml from scratch, crawling all index.html files."""

import os
import json
from datetime import date

BASE    = os.path.dirname(os.path.abspath(__file__))
DOMAIN  = 'https://sifufinds.com'
TODAY   = date.today().isoformat()

# Directories to exclude from crawl
EXCLUDED_DIRS = {
    'agents', 'firecrawl', 'geo-content-writer', 'supabase',
    '.git', '.github', '.venv', '__pycache__', 'node_modules',
    '.claude', 'data',
}

# Priority and changefreq by URL pattern
def classify(url: str):
    path = url.replace(DOMAIN, '').strip('/')

    if path == '':
        return '1.0', 'daily'
    if path in ('tips', 'tips/', 'casino', 'casino/', 'odds', 'odds/', 'blog', 'blog/'):
        return '0.9', 'hourly'
    if path.startswith('tips/world-cup-2026'):
        return '0.9', 'daily'
    if path.startswith('blog/') and path.count('/') == 1:
        return '0.8', 'weekly'
    if path.startswith('countries/') and path.count('/') == 1:
        return '0.9', 'daily'
    if path.startswith('countries/') and path.count('/') == 2:
        # city page
        return '0.75', 'weekly'
    if path.startswith('bookmakers/') and path.count('/') == 1:
        # main bookmaker review
        return '0.85', 'weekly'
    if path.startswith('bookmakers/') and path.count('/') == 2:
        # bookmaker × country
        return '0.8', 'weekly'
    if path.startswith('betting/') and path.count('/') == 1:
        # payment method hub
        return '0.8', 'weekly'
    if path.startswith('betting/') and path.count('/') == 2:
        # payment × country or sport × country
        return '0.75', 'weekly'
    if path.startswith('guides/'):
        return '0.7', 'monthly'
    if path.startswith('bonuses/'):
        return '0.75', 'weekly'
    if path.startswith('casino/') or path.startswith('odds/'):
        return '0.7', 'daily'
    if path.startswith('about') or path.startswith('contact'):
        return '0.4', 'monthly'

    return '0.6', 'monthly'


def collect_urls():
    urls = []
    for root, dirs, files in os.walk(BASE):
        # Prune excluded directories in-place
        dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS and not d.startswith('.')]

        if 'index.html' not in files:
            continue

        rel = os.path.relpath(root, BASE)
        if rel == '.':
            url = f'{DOMAIN}/'
        else:
            rel_norm = rel.replace(os.sep, '/')
            url = f'{DOMAIN}/{rel_norm}/'

        # Skip analytics, google verification pages
        if any(skip in url for skip in ['/analytics', '/google3', '/gen_', '/.', '/data/']):
            continue

        urls.append(url)

    return sorted(set(urls))


def build_sitemap(urls):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
        '',
        '  <!-- Auto-generated by gen_sitemap.py — ' + TODAY + ' -->',
        '',
    ]

    # Group by section for readability
    sections = {
        'CORE': [],
        'COUNTRIES': [],
        'CITY': [],
        'BOOKMAKERS': [],
        'BETTING-PAYMENT': [],
        'BETTING-SPORT': [],
        'TIPS': [],
        'WC2026': [],
        'GUIDES': [],
        'BLOG': [],
        'OTHER': [],
    }

    for url in urls:
        path = url.replace(DOMAIN, '').strip('/')
        if path in ('', 'tips', 'casino', 'odds', 'blog', 'countries', 'bookmakers',
                    'betting', 'guides', 'bonuses', 'about', 'contact'):
            sections['CORE'].append(url)
        elif path.startswith('countries/') and path.count('/') == 1:
            sections['COUNTRIES'].append(url)
        elif path.startswith('countries/'):
            sections['CITY'].append(url)
        elif path.startswith('bookmakers/') and path.count('/') == 1:
            sections['BOOKMAKERS'].append(url)
        elif path.startswith('bookmakers/'):
            sections['BOOKMAKERS'].append(url)
        elif path.startswith('betting/') and any(
            pm in path for pm in ['mpesa', 'mtn-momo', 'airtel-money', 'opay', 'orange-money',
                                   'ecocash', 'telebirr', 'bank-transfer', 'vodacom']
        ):
            sections['BETTING-PAYMENT'].append(url)
        elif path.startswith('betting/') and any(
            sp in path for sp in ['football-betting', 'basketball-betting', 'cricket-betting',
                                   'rugby-betting', 'tennis-betting']
        ):
            sections['BETTING-SPORT'].append(url)
        elif 'world-cup-2026' in path:
            sections['WC2026'].append(url)
        elif path.startswith('tips/'):
            sections['TIPS'].append(url)
        elif path.startswith('guides/'):
            sections['GUIDES'].append(url)
        elif path.startswith('blog/') and path != 'blog':
            sections['BLOG'].append(url)
        else:
            sections['OTHER'].append(url)

    section_labels = {
        'CORE': 'CORE PAGES',
        'COUNTRIES': 'COUNTRY PAGES',
        'CITY': 'CITY PAGES',
        'BOOKMAKERS': 'BOOKMAKER PAGES',
        'BETTING-PAYMENT': 'PAYMENT METHOD PAGES',
        'BETTING-SPORT': 'SPORT BETTING PAGES',
        'TIPS': 'TIPS PAGES',
        'WC2026': 'WORLD CUP 2026',
        'GUIDES': 'GUIDES',
        'BLOG': 'BLOG POSTS',
        'OTHER': 'OTHER PAGES',
    }

    for section_key, section_urls in sections.items():
        if not section_urls:
            continue
        label = section_labels[section_key]
        lines.append(f'  <!-- ── {label} {"─" * max(1, 60 - len(label))} -->')
        for url in sorted(section_urls):
            priority, changefreq = classify(url)
            lines.append('  <url>')
            lines.append(f'    <loc>{url}</loc>')
            lines.append(f'    <lastmod>{TODAY}</lastmod>')
            lines.append(f'    <changefreq>{changefreq}</changefreq>')
            lines.append(f'    <priority>{priority}</priority>')
            lines.append('  </url>')
        lines.append('')

    lines.append('</urlset>')
    return '\n'.join(lines)


def main():
    urls = collect_urls()
    print(f'  Found {len(urls)} indexable URLs')

    sitemap = build_sitemap(urls)

    out_path = os.path.join(BASE, 'sitemap.xml')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(sitemap)

    line_count = sitemap.count('\n')
    print(f'  ✓  sitemap.xml written — {len(urls)} URLs, {line_count} lines')

    # Print breakdown
    for section, count in [
        ('Core',     sum(1 for u in urls if u.replace(DOMAIN,'').strip('/') in ('', 'tips','casino','odds','blog','countries','bookmakers','betting','guides','bonuses','about','contact'))),
        ('Countries', sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('countries/') and u.replace(DOMAIN,'').strip('/').count('/') == 1)),
        ('Cities',    sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('countries/') and u.replace(DOMAIN,'').strip('/').count('/') >= 2)),
        ('Bookmakers',sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('bookmakers/'))),
        ('Betting (payment)',  sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('betting/') and any(pm in u for pm in ['mpesa','mtn-momo','airtel','opay','orange-money','ecocash','telebirr','bank-transfer','vodacom']))),
        ('Betting (sport)',    sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('betting/') and any(s in u for s in ['football-betting','basketball','cricket','rugby','tennis']))),
        ('WC2026',    sum(1 for u in urls if 'world-cup-2026' in u)),
        ('Tips',      sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('tips/'))),
        ('Guides',    sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('guides/'))),
        ('Blog posts',sum(1 for u in urls if u.replace(DOMAIN,'').strip('/').startswith('blog/') and u.replace(DOMAIN,'').strip('/') != 'blog')),
    ]:
        print(f'    {section:<25} {count:>4}')


if __name__ == '__main__':
    main()
