#!/usr/bin/env python3
"""Generate Wave 3 city pages — capital/major cities for the 23 established African countries."""

import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_city_pages import make_city_page, BASE

CITIES = [
    # ── Tanzania ─────────────────────────────────────────────────────────
    {
        'path': 'countries/tanzania/dar-es-salaam',
        'slug': 'dar-es-salaam',
        'city': 'Dar es Salaam',
        'country': 'Tanzania',
        'country_code': 'TZ',
        'country_slug': 'tanzania',
        'flag': '🇹🇿',
        'currency': 'TZS',
        'symbol': 'TSh',
        'regulator': 'Gaming Board of Tanzania (GBT)',
        'population': "Tanzania's largest city and former capital with 6+ million people",
        'about': "Dar es Salaam is Tanzania's commercial hub and the biggest sports betting market in the country. Bettors use M-Pesa via *150*00#, Airtel Money, Tigopesa, and Halopesa at GBT-licensed bookmakers. Sportybet, 1xBet Tanzania, and Betway Tanzania are the most popular platforms. Dar es Salaam has the highest concentration of licensed betting shops in East Africa outside of Nairobi.",
        'payments': ['M-Pesa (Vodacom)', 'Airtel Money', 'Tigopesa', 'Halopesa', 'Bank Transfer'],
        'popular_leagues': ['Tanzania Premier League', 'CAF Champions League', 'AFCON', 'Premier League', 'World Cup 2026'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/tanzania/arusha',
        'slug': 'arusha',
        'city': 'Arusha',
        'country': 'Tanzania',
        'country_code': 'TZ',
        'country_slug': 'tanzania',
        'flag': '🇹🇿',
        'currency': 'TZS',
        'symbol': 'TSh',
        'regulator': 'Gaming Board of Tanzania (GBT)',
        'population': "Tourism capital of Tanzania with 1.7+ million people in the metro area",
        'about': "Arusha is Tanzania's gateway to the Serengeti and Kilimanjaro, and a fast-growing betting market. GBT-licensed bookmakers serve Arusha bettors via M-Pesa, Tigopesa, and Airtel Money. The city's young, internationally connected population follows the Premier League closely alongside the Tanzania Premier League.",
        'payments': ['M-Pesa (Vodacom)', 'Airtel Money', 'Tigopesa', 'Bank Transfer'],
        'popular_leagues': ['Tanzania Premier League', 'Premier League', 'CAF Champions League', 'AFCON'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Uganda ────────────────────────────────────────────────────────────
    {
        'path': 'countries/uganda/kampala',
        'slug': 'kampala',
        'city': 'Kampala',
        'country': 'Uganda',
        'country_code': 'UG',
        'country_slug': 'uganda',
        'flag': '🇺🇬',
        'currency': 'UGX',
        'symbol': 'USh',
        'regulator': 'Uganda National Gaming Board (UNGB)',
        'population': "Uganda's capital city with 3.5+ million people",
        'about': "Kampala is Uganda's capital and the largest betting market in the country. MTN MoMo and Airtel Money are the dominant payment methods at UNGB-licensed bookmakers. Betway Uganda, 1xBet Uganda, and Betika are most popular. Ugandans are passionate about AFCON, the Premier League, and the Uganda Premier League. Kampala has a dense network of licensed betting shops in Kabalagala, Wandegeya, and the city centre.",
        'payments': ['MTN MoMo', 'Airtel Money', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Uganda Premier League', 'AFCON', 'CAF Champions League', 'Premier League', 'La Liga'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/uganda/entebbe',
        'slug': 'entebbe',
        'city': 'Entebbe',
        'country': 'Uganda',
        'country_code': 'UG',
        'country_slug': 'uganda',
        'flag': '🇺🇬',
        'currency': 'UGX',
        'symbol': 'USh',
        'regulator': 'Uganda National Gaming Board (UNGB)',
        'population': "Uganda's international gateway city on Lake Victoria with 70,000+ people",
        'about': "Entebbe is Uganda's aviation hub and a growing betting market. UNGB-licensed betting sites serve Entebbe residents via MTN MoMo and Airtel Money. As a travel hub, Entebbe bettors follow international football heavily including the Premier League, Champions League, and AFCON.",
        'payments': ['MTN MoMo', 'Airtel Money', 'Bank Transfer'],
        'popular_leagues': ['Uganda Premier League', 'Premier League', 'Champions League', 'AFCON'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Zambia ────────────────────────────────────────────────────────────
    {
        'path': 'countries/zambia/lusaka',
        'slug': 'lusaka',
        'city': 'Lusaka',
        'country': 'Zambia',
        'country_code': 'ZM',
        'country_slug': 'zambia',
        'flag': '🇿🇲',
        'currency': 'ZMW',
        'symbol': 'ZK',
        'regulator': 'Zambia Gambling Commission (ZGC)',
        'population': "Zambia's capital and largest city with 3+ million people",
        'about': "Lusaka is Zambia's capital and the biggest sports betting market in the country. ZGC-licensed bookmakers accept MTN MoMo and Airtel Money for instant deposits. Betway Zambia, Sportybet Zambia, and 1xBet Zambia are the leading platforms. Lusaka bettors are passionate about the FAZ Super Division (Zambia's top football league), AFCON, and the CAF Champions League.",
        'payments': ['MTN MoMo', 'Airtel Money', 'Zamtel Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['FAZ Super Division (Lusaka Dynamos, Nkana FC)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/zambia/kitwe',
        'slug': 'kitwe',
        'city': 'Kitwe',
        'country': 'Zambia',
        'country_code': 'ZM',
        'country_slug': 'zambia',
        'flag': '🇿🇲',
        'currency': 'ZMW',
        'symbol': 'ZK',
        'regulator': 'Zambia Gambling Commission (ZGC)',
        'population': "Zambia's second largest city on the Copperbelt with 700,000+ people",
        'about': "Kitwe is Zambia's mining capital and a major betting market on the Copperbelt. ZGC-licensed bookmakers serve Kitwe bettors via MTN MoMo and Airtel Money. Home to Nkana FC — one of Zambia's most storied football clubs — Kitwe has one of the most passionate football betting cultures in the country.",
        'payments': ['MTN MoMo', 'Airtel Money', 'Bank Transfer'],
        'popular_leagues': ['FAZ Super Division (Nkana FC home)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Ethiopia ──────────────────────────────────────────────────────────
    {
        'path': 'countries/ethiopia/addis-ababa',
        'slug': 'addis-ababa',
        'city': 'Addis Ababa',
        'country': 'Ethiopia',
        'country_code': 'ET',
        'country_slug': 'ethiopia',
        'flag': '🇪🇹',
        'currency': 'ETB',
        'symbol': 'Br',
        'regulator': 'National Lottery Administration (NLA Ethiopia)',
        'population': "Africa's third largest city and Ethiopia's capital with 5+ million people",
        'about': "Addis Ababa is Ethiopia's capital and the seat of the African Union. It is the largest and fastest-growing betting market in East Africa after Nairobi. NLA-licensed bookmakers accept Telebirr (Ethio Telecom), CBE Birr, and Bank Transfer. Ethiopia's young population (median age 18) is highly engaged with AFCON — Ethiopia qualified for the 2023 edition — and the Premier League. 1xBet Ethiopia and Betway Ethiopia lead the market.",
        'payments': ['Telebirr', 'CBE Birr', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Ethiopian Premier League', 'AFCON', 'CAF Champions League', 'Premier League', 'World Cup 2026'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Rwanda ────────────────────────────────────────────────────────────
    {
        'path': 'countries/rwanda/kigali',
        'slug': 'kigali',
        'city': 'Kigali',
        'country': 'Rwanda',
        'country_code': 'RW',
        'country_slug': 'rwanda',
        'flag': '🇷🇼',
        'currency': 'RWF',
        'symbol': 'RWF',
        'regulator': 'Rwanda Gaming Commission (RGC)',
        'population': "Rwanda's capital and only major city with 1.5+ million people",
        'about': "Kigali is Rwanda's capital and one of Africa's cleanest, most tech-forward cities. The Rwanda Gaming Commission (RGC) regulates all betting operators. RGC-licensed bookmakers accept MTN MoMo and Airtel Money for instant deposits. Betway Rwanda and 1xBet Rwanda are the market leaders. Rwandans follow the APR FC (Army's team) and Rayon Sports in the Rwanda Premier League alongside the Premier League and AFCON.",
        'payments': ['MTN MoMo', 'Airtel Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Rwanda Premier League (APR FC, Rayon Sports)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Morocco ───────────────────────────────────────────────────────────
    {
        'path': 'countries/morocco/casablanca',
        'slug': 'casablanca',
        'city': 'Casablanca',
        'country': 'Morocco',
        'country_code': 'MA',
        'country_slug': 'morocco',
        'flag': '🇲🇦',
        'currency': 'MAD',
        'symbol': 'DH',
        'regulator': 'Société Marocaine des Jeux et des Sports (MDJS)',
        'population': "Morocco's largest city with 4+ million people",
        'about': "Casablanca is Morocco's economic capital and the dominant betting market in North Africa. MDJS (the state gambling authority) regulates legal operators. Casablanca bettors primarily use CMI bank cards, bank transfer, and Visa/Mastercard. Morocco is a football-crazy nation — the Atlas Lions reached the 2022 World Cup semi-final — and interest in the 2026 World Cup (co-hosted by Morocco) is at fever pitch. Raja Casablanca and Wydad Casablanca are among Africa's most celebrated clubs.",
        'payments': ['CMI Bank Cards', 'Visa', 'Mastercard', 'Bank Transfer', 'Maroc Telecom Money'],
        'popular_leagues': ['Botola Pro (Raja Casablanca, Wydad AC)', 'World Cup 2026 (Morocco co-host)', 'AFCON', 'CAF Champions League', 'La Liga', 'Ligue 1'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/morocco/marrakech',
        'slug': 'marrakech',
        'city': 'Marrakech',
        'country': 'Morocco',
        'country_code': 'MA',
        'country_slug': 'morocco',
        'flag': '🇲🇦',
        'currency': 'MAD',
        'symbol': 'DH',
        'regulator': 'Société Marocaine des Jeux et des Sports (MDJS)',
        'population': "Morocco's cultural capital and major tourist city with 1.2+ million people",
        'about': "Marrakech is Morocco's famous Red City and a growing sports betting market. MDJS-licensed bookmakers serve Marrakech bettors who primarily use Visa, Mastercard, and bank transfer. Marrakech Stade de Marrakech is a World Cup 2026 venue, creating massive local betting interest. Kawkab AC Marrakech plays in the Botola Pro.",
        'payments': ['Visa', 'Mastercard', 'Bank Transfer', 'CMI Bank Cards'],
        'popular_leagues': ['Botola Pro', 'World Cup 2026 (Marrakech venue)', 'AFCON', 'CAF Champions League', 'La Liga'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/morocco/rabat',
        'slug': 'rabat',
        'city': 'Rabat',
        'country': 'Morocco',
        'country_code': 'MA',
        'country_slug': 'morocco',
        'flag': '🇲🇦',
        'currency': 'MAD',
        'symbol': 'DH',
        'regulator': 'Société Marocaine des Jeux et des Sports (MDJS)',
        'population': "Morocco's capital city with 1.9+ million people",
        'about': "Rabat is Morocco's political capital and home to a large educated population of sports bettors. MDJS-licensed operators are accessible via Visa, Mastercard, and CMI bank cards. As co-host of the 2026 World Cup, Morocco's capital city will see international football betting reach historic levels. FAR Rabat is the local top-flight club.",
        'payments': ['Visa', 'Mastercard', 'Bank Transfer', 'CMI Bank Cards'],
        'popular_leagues': ['Botola Pro', 'World Cup 2026', 'AFCON', 'CAF Champions League', 'La Liga', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Egypt ─────────────────────────────────────────────────────────────
    {
        'path': 'countries/egypt/cairo',
        'slug': 'cairo',
        'city': 'Cairo',
        'country': 'Egypt',
        'country_code': 'EG',
        'country_slug': 'egypt',
        'flag': '🇪🇬',
        'currency': 'EGP',
        'symbol': 'EGP',
        'regulator': 'Egyptian Gaming Authority (EGA)',
        'population': "Africa's largest city with 22+ million people in the Greater Cairo area",
        'about': "Cairo is Africa's most populous city and the heart of North African football culture. Cairo bettors use Vodafone Cash, Fawry, Instapay, and bank transfer at licensed offshore bookmakers. Egypt is a football nation of the highest order — Al-Ahly and Zamalek are the two most supported clubs on the continent. Cairo bettors follow AFCON (Egypt won it a record 7 times), the Egyptian Premier League, and European football intensely.",
        'payments': ['Vodafone Cash', 'Fawry', 'Instapay', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Egyptian Premier League (Al-Ahly, Zamalek)', 'AFCON', 'CAF Champions League', 'Premier League', 'Champions League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/egypt/alexandria',
        'slug': 'alexandria',
        'city': 'Alexandria',
        'country': 'Egypt',
        'country_code': 'EG',
        'country_slug': 'egypt',
        'flag': '🇪🇬',
        'currency': 'EGP',
        'symbol': 'EGP',
        'regulator': 'Egyptian Gaming Authority (EGA)',
        'population': "Egypt's second largest city with 5+ million people",
        'about': "Alexandria is Egypt's Mediterranean port city and the country's second largest betting market. EGA-licensed offshore operators serve Alexandria via Vodafone Cash, Fawry, and Visa/Mastercard. Alexandria has passionate fans of Ittihad Alexandria and AFCON matches.",
        'payments': ['Vodafone Cash', 'Fawry', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Egyptian Premier League', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Angola ────────────────────────────────────────────────────────────
    {
        'path': 'countries/angola/luanda',
        'slug': 'luanda',
        'city': 'Luanda',
        'country': 'Angola',
        'country_code': 'AO',
        'country_slug': 'angola',
        'flag': '🇦🇴',
        'currency': 'AOA',
        'symbol': 'Kz',
        'regulator': 'Instituto de Supervisão de Jogos (ISJ Angola)',
        'population': "Angola's capital and Africa's third most expensive city with 9+ million people",
        'about': "Luanda is Angola's capital and the largest Portuguese-speaking city in Africa. ISJ-licensed bookmakers serve Luanda's fast-growing betting market via Unitel Money, Multicaixa, and bank transfer. Angola is passionate about AFCON — the Palancas Negras qualified for AFCON 2023 and 2024 — as well as the Girabola (Angola's Premier League) and the Portuguese Liga NOS.",
        'payments': ['Unitel Money', 'Multicaixa Express', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Girabola (Petro de Luanda, Primeiro de Agosto)', 'AFCON', 'CAF Champions League', 'Liga NOS (Portugal)', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Mozambique ────────────────────────────────────────────────────────
    {
        'path': 'countries/mozambique/maputo',
        'slug': 'maputo',
        'city': 'Maputo',
        'country': 'Mozambique',
        'country_code': 'MZ',
        'country_slug': 'mozambique',
        'flag': '🇲🇿',
        'currency': 'MZN',
        'symbol': 'MT',
        'regulator': 'Inspecção de Jogos de Moçambique (IJM)',
        'population': "Mozambique's capital with 2.7+ million people",
        'about': "Maputo is Mozambique's vibrant capital on the Indian Ocean. IJM-licensed bookmakers serve Maputo bettors via M-Pesa (Vodacom Mozambique), mKesh, and Airtel Money. Mozambique shares a deep football passion with South Africa and Brazil — the local Moçambola (Premier League) and AFCON are the top markets.",
        'payments': ['M-Pesa (Vodacom MZ)', 'mKesh', 'Airtel Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Moçambola', 'AFCON', 'CAF Champions League', 'Premier League', 'Brazilian Série A'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/mozambique/beira',
        'slug': 'beira',
        'city': 'Beira',
        'country': 'Mozambique',
        'country_code': 'MZ',
        'country_slug': 'mozambique',
        'flag': '🇲🇿',
        'currency': 'MZN',
        'symbol': 'MT',
        'regulator': 'Inspecção de Jogos de Moçambique (IJM)',
        'population': "Mozambique's second largest city and port with 600,000+ people",
        'about': "Beira is Mozambique's major port city and the hub for central Mozambique's betting market. IJM-licensed bookmakers serve Beira via M-Pesa Mozambique and bank transfer. The city has strong ties to the Moçambola and fervent AFCON support.",
        'payments': ['M-Pesa (Vodacom MZ)', 'Airtel Money', 'Bank Transfer'],
        'popular_leagues': ['Moçambola', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Cameroon ─────────────────────────────────────────────────────────
    {
        'path': 'countries/cameroon/douala',
        'slug': 'douala',
        'city': 'Douala',
        'country': 'Cameroon',
        'country_code': 'CM',
        'country_slug': 'cameroon',
        'flag': '🇨🇲',
        'currency': 'XAF',
        'symbol': 'CFA',
        'regulator': 'Autorité de Régulation des Jeux (ARJ Cameroun)',
        'population': "Cameroon's economic capital with 4+ million people",
        'about': "Douala is Cameroon's largest city and economic capital. MTN MoMo and Orange Money are the primary payment methods at ARJ-licensed bookmakers. Cameroon is one of Africa's most football-passionate countries — the Indomitable Lions qualified for the 2022 World Cup and are regular AFCON contenders. Douala is home to Coton Sport de Garoua's fierce rivals and a betting market that explodes during AFCON and World Cup.",
        'payments': ['MTN MoMo', 'Orange Money', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['MTN Elite One (Cameroon top flight)', 'AFCON', 'CAF Champions League', 'Ligue 1 (France)', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/cameroon/yaounde',
        'slug': 'yaounde',
        'city': 'Yaoundé',
        'country': 'Cameroon',
        'country_code': 'CM',
        'country_slug': 'cameroon',
        'flag': '🇨🇲',
        'currency': 'XAF',
        'symbol': 'CFA',
        'regulator': 'Autorité de Régulation des Jeux (ARJ Cameroun)',
        'population': "Cameroon's political capital with 3.5+ million people",
        'about': "Yaoundé is Cameroon's capital and hosted the 2022 AFCON tournament. MTN MoMo and Orange Money are the dominant payment methods. The capital city bettors are passionate about Samuel Eto'o's legacy (he is now President of the Cameroon Football Federation), the Indomitable Lions, and AFCON.",
        'payments': ['MTN MoMo', 'Orange Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['MTN Elite One', 'AFCON', 'CAF Champions League', 'Ligue 1 (France)', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Ivory Coast ───────────────────────────────────────────────────────
    {
        'path': 'countries/ivory-coast/abidjan',
        'slug': 'abidjan',
        'city': 'Abidjan',
        'country': 'Ivory Coast',
        'country_code': 'CI',
        'country_slug': 'ivory-coast',
        'flag': '🇨🇮',
        'currency': 'XOF',
        'symbol': 'CFA',
        'regulator': 'Autorité Nationale des Jeux (LFDJ/ANJ Côte d\'Ivoire)',
        'population': "Ivory Coast's economic capital and largest city with 5+ million people",
        'about': "Abidjan is the commercial capital of Ivory Coast and West Africa's most vibrant betting market. Orange Money, Wave, and MTN MoMo are the dominant payment methods. Ivory Coast hosted AFCON 2023/24 (the Éléphants won it at home) making it Africa's most celebrated football moment in recent years. ASEC Mimosas and Africa Sports are the top clubs. 1xBet and Betway Côte d'Ivoire lead the licensed market.",
        'payments': ['Orange Money', 'Wave', 'MTN MoMo', 'Moov Money', 'Bank Transfer'],
        'popular_leagues': ['MTN Ligue 1 (ASEC Mimosas, Africa Sports)', 'AFCON', 'CAF Champions League', 'Ligue 1 (France)', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Senegal ───────────────────────────────────────────────────────────
    {
        'path': 'countries/senegal/dakar',
        'slug': 'dakar',
        'city': 'Dakar',
        'country': 'Senegal',
        'country_code': 'SN',
        'country_slug': 'senegal',
        'flag': '🇸🇳',
        'currency': 'XOF',
        'symbol': 'CFA',
        'regulator': 'Autorité de Régulation des Jeux (ARJ Sénégal)',
        'population': "Senegal's capital and gateway city with 3.9+ million people",
        'about': "Dakar is Senegal's capital and the biggest sports betting market in French-speaking West Africa. Orange Money, Wave, and Free Money are the primary payment methods. Senegal is the reigning AFCON champion — the Lions of Teranga won AFCON 2021/22 and 2023/24 — making betting on Senegalese football a national pastime. Sadio Mané remains a national hero. 1xBet and Betway Sénégal are the leading licensed platforms.",
        'payments': ['Orange Money', 'Wave', 'Free Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Ligue 1 Sénégal', 'AFCON (Senegal champions)', 'CAF Champions League', 'Ligue 1 (France)', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Zimbabwe ──────────────────────────────────────────────────────────
    {
        'path': 'countries/zimbabwe/harare',
        'slug': 'harare',
        'city': 'Harare',
        'country': 'Zimbabwe',
        'country_code': 'ZW',
        'country_slug': 'zimbabwe',
        'flag': '🇿🇼',
        'currency': 'USD',
        'symbol': 'USD',
        'regulator': 'Betting Control and Licensing Board (BCLB Zimbabwe)',
        'population': "Zimbabwe's capital with 2.1+ million people",
        'about': "Harare is Zimbabwe's capital and the largest betting market in the country. EcoCash (Econet) is the dominant payment method — used by over 8 million Zimbabweans — followed by OneMoney and Telecash. BCLB-licensed bookmakers include BetZim, TopBet, and Sportybet Zimbabwe. Harare bettors follow Dynamos FC and CAPS United in the Castle Lager Premier Soccer League (PSL) alongside the Premier League and AFCON.",
        'payments': ['EcoCash', 'OneMoney', 'Telecash', 'Bank Transfer (USD)', 'Visa'],
        'popular_leagues': ['Castle Lager PSL (Dynamos, CAPS United)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/zimbabwe/bulawayo',
        'slug': 'bulawayo',
        'city': 'Bulawayo',
        'country': 'Zimbabwe',
        'country_code': 'ZW',
        'country_slug': 'zimbabwe',
        'flag': '🇿🇼',
        'currency': 'USD',
        'symbol': 'USD',
        'regulator': 'Betting Control and Licensing Board (BCLB Zimbabwe)',
        'population': "Zimbabwe's second largest city with 700,000+ people",
        'about': "Bulawayo is Zimbabwe's second city and the Ndebele heartland. BCLB-licensed bookmakers serve Bulawayo bettors via EcoCash and bank transfer. Highlanders FC (based in Bulawayo) is one of Zimbabwe's most followed clubs, giving local bettors a passionate connection to the Castle Lager PSL.",
        'payments': ['EcoCash', 'OneMoney', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Castle Lager PSL (Highlanders FC)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Malawi ────────────────────────────────────────────────────────────
    {
        'path': 'countries/malawi/lilongwe',
        'slug': 'lilongwe',
        'city': 'Lilongwe',
        'country': 'Malawi',
        'country_code': 'MW',
        'country_slug': 'malawi',
        'flag': '🇲🇼',
        'currency': 'MWK',
        'symbol': 'MK',
        'regulator': 'Gaming Board of Malawi (GBM)',
        'population': "Malawi's capital with 1.2+ million people",
        'about': "Lilongwe is Malawi's capital and the largest betting market in the country. Airtel Money and TNM Mpamba (Telekom Networks Malawi) are the primary payment methods at GBM-licensed bookmakers. Sportybet Malawi and 1xBet Malawi are the leading platforms. Malawians are passionate about the TNM Super League and AFCON.",
        'payments': ['Airtel Money', 'TNM Mpamba', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['TNM Super League', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/malawi/blantyre',
        'slug': 'blantyre',
        'city': 'Blantyre',
        'country': 'Malawi',
        'country_code': 'MW',
        'country_slug': 'malawi',
        'flag': '🇲🇼',
        'currency': 'MWK',
        'symbol': 'MK',
        'regulator': 'Gaming Board of Malawi (GBM)',
        'population': "Malawi's commercial capital with 1+ million people",
        'about': "Blantyre is Malawi's commercial hub and the home of Be Forward Wanderers and Nyasa Big Bullets — the two biggest football clubs in Malawi. GBM-licensed betting sites serve Blantyre via Airtel Money and TNM Mpamba. The fierce Bullets vs Wanderers derby makes Blantyre one of the most passionate football betting cities in southern Africa.",
        'payments': ['Airtel Money', 'TNM Mpamba', 'Bank Transfer'],
        'popular_leagues': ['TNM Super League (Big Bullets, Wanderers)', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Botswana ──────────────────────────────────────────────────────────
    {
        'path': 'countries/botswana/gaborone',
        'slug': 'gaborone',
        'city': 'Gaborone',
        'country': 'Botswana',
        'country_code': 'BW',
        'country_slug': 'botswana',
        'flag': '🇧🇼',
        'currency': 'BWP',
        'symbol': 'P',
        'regulator': 'Gambling Authority of Botswana (GAB)',
        'population': "Botswana's capital with 500,000+ people",
        'about': "Gaborone is Botswana's capital and the primary betting market in the country. GAB-licensed bookmakers include Betway Botswana and 1xBet Botswana. Orange Money, Mascom MyZaka, and bank transfer are the main payment methods. Gaborone bettors are passionate about the Botswana Premier League and heavily follow South African PSL and the Premier League.",
        'payments': ['Orange Money', 'Mascom MyZaka', 'Bank Transfer', 'Visa', 'Mastercard'],
        'popular_leagues': ['Botswana Premier League', 'South African PSL', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Namibia ───────────────────────────────────────────────────────────
    {
        'path': 'countries/namibia/windhoek',
        'slug': 'windhoek',
        'city': 'Windhoek',
        'country': 'Namibia',
        'country_code': 'NA',
        'country_slug': 'namibia',
        'flag': '🇳🇦',
        'currency': 'NAD',
        'symbol': 'N$',
        'regulator': 'Gambling Board of Namibia (GBN)',
        'population': "Namibia's capital with 450,000+ people",
        'about': "Windhoek is Namibia's capital and the main sports betting market in southern Africa's most sparsely populated country. GBN-licensed bookmakers operate via Bank Windhoek, FNB Namibia, and Nedbank Namibia transfers. Namibia qualified for AFCON 2024 for the first time, sparking massive national excitement. The Brave Warriors' historic debut made Windhoek a hotspot for AFCON betting.",
        'payments': ['Bank Windhoek', 'FNB Namibia', 'Nedbank Namibia', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Namibia Premier League', 'AFCON', 'CAF Champions League', 'South African PSL', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── DR Congo ─────────────────────────────────────────────────────────
    {
        'path': 'countries/dr-congo/kinshasa',
        'slug': 'kinshasa',
        'city': 'Kinshasa',
        'country': 'DR Congo',
        'country_code': 'CD',
        'country_slug': 'dr-congo',
        'flag': '🇨🇩',
        'currency': 'CDF',
        'symbol': 'FC',
        'regulator': 'Autorité de Régulation des Jeux de Hasard (ARJH DRC)',
        'population': "Africa's third largest city with 16+ million people",
        'about': "Kinshasa is the capital of DR Congo and one of Africa's most populous cities, with a growing and passionate sports betting market. ARJH-licensed bookmakers accept Airtel Money, Orange Money, M-Pesa (Vodacom Congo), and bank transfer. DR Congo is a AFCON powerhouse — the Léopards are three-time champions. Kinshasa bettors follow TP Mazembe (based in Lubumbashi but beloved nationally) and AS Vita Club in the Linafoot Premier League.",
        'payments': ['Airtel Money', 'Orange Money', 'M-Pesa (Vodacom)', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Linafoot Premier League (AS Vita Club, DC Motema Pembe)', 'AFCON', 'CAF Champions League', 'Premier League', 'Ligue 1 (France)'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    {
        'path': 'countries/dr-congo/lubumbashi',
        'slug': 'lubumbashi',
        'city': 'Lubumbashi',
        'country': 'DR Congo',
        'country_code': 'CD',
        'country_slug': 'dr-congo',
        'flag': '🇨🇩',
        'currency': 'CDF',
        'symbol': 'FC',
        'regulator': 'Autorité de Régulation des Jeux de Hasard (ARJH DRC)',
        'population': "DRC's mining capital with 2.5+ million people",
        'about': "Lubumbashi is DRC's copper mining capital and home to TP Mazembe — Africa's most decorated club of the last two decades (5× CAF Champions League titles). ARJH-licensed bookmakers serve Lubumbashi via Airtel Money and Orange Money. During CAF Champions League matches, Lubumbashi becomes one of Africa's most electrifying betting markets.",
        'payments': ['Airtel Money', 'Orange Money', 'Bank Transfer'],
        'popular_leagues': ['Linafoot (TP Mazembe home)', 'CAF Champions League', 'AFCON', 'Premier League', 'Ligue 1 (France)'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Sierra Leone ─────────────────────────────────────────────────────
    {
        'path': 'countries/sierra-leone/freetown',
        'slug': 'freetown',
        'city': 'Freetown',
        'country': 'Sierra Leone',
        'country_code': 'SL',
        'country_slug': 'sierra-leone',
        'flag': '🇸🇱',
        'currency': 'SLL',
        'symbol': 'Le',
        'regulator': 'National Lottery Authority of Sierra Leone (NLA-SL)',
        'population': "Sierra Leone's capital with 1.5+ million people",
        'about': "Freetown is Sierra Leone's capital and the only major betting market in the country. NLA-SL-licensed bookmakers operate via Afrimoney and Orange Money. Sierra Leone qualified for AFCON 2022 for the first time in 26 years, reigniting national football passion. The Leone Stars' return to the continental stage sparked betting growth across Freetown.",
        'payments': ['Afrimoney', 'Orange Money', 'Bank Transfer'],
        'popular_leagues': ['Sierra Leone Premier League', 'AFCON', 'CAF Champions League', 'Premier League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
    # ── Liberia ───────────────────────────────────────────────────────────
    {
        'path': 'countries/liberia/monrovia',
        'slug': 'monrovia',
        'city': 'Monrovia',
        'country': 'Liberia',
        'country_code': 'LR',
        'country_slug': 'liberia',
        'flag': '🇱🇷',
        'currency': 'LRD',
        'symbol': 'L$',
        'regulator': 'Gambling Control Commission of Liberia (GCC)',
        'population': "Liberia's capital with 1.5+ million people",
        'about': "Monrovia is Liberia's capital and the country's sole major betting market. GCC-licensed bookmakers serve Monrovia via Orange Money and bank transfer. Liberians follow the Premier League obsessively — the country has produced notable players including George Weah (former FIFA World Player of the Year and ex-President). Betting on the Premier League and AFCON are the biggest markets.",
        'payments': ['Orange Money', 'Bank Transfer', 'Visa'],
        'popular_leagues': ['Liberia Lone Star League', 'Premier League', 'AFCON', 'CAF Champions League'],
        'assets_prefix': '../../../',
        'country_prefix': '../../',
        'depth': 3,
    },
]


if __name__ == '__main__':
    for city in CITIES:
        out_dir = os.path.join(BASE, city['path'])
        os.makedirs(out_dir, exist_ok=True)
        html = make_city_page(city)
        out_path = os.path.join(out_dir, 'index.html')
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'  ✓  /{city["path"]}/')
    print(f'\n✅ Generated {len(CITIES)} Wave 3 city pages')
