"""
Builds and saves blog/ticker.json and blog/ticker-data.js with live sports headlines.
ticker-data.js injects window.TICKER_DATA so the page works on file:// protocol.
Called by the blog writer agent each run so the ticker stays current.
"""
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.news_fetcher import build_ticker_items

BLOG_DIR = Path(__file__).parent.parent.parent.parent / "blog"
TICKER_PATH = BLOG_DIR / "ticker.json"
TICKER_JS_PATH = BLOG_DIR / "ticker-data.js"

CAT_ICONS = {
    "football":   "⚽ FOOTBALL",
    "transfers":  "🔄 TRANSFER",
    "basketball": "🏀 BASKETBALL",
    "tennis":     "🎾 TENNIS",
    "cricket":    "🏏 CRICKET",
    "rugby":      "🏉 RUGBY",
    "igaming":    "🎮 iGAMING",
    "general":    "🏟️ SPORT",
}


def build_and_save(max_items: int = 24) -> list:
    """Fetch live headlines, write ticker.json and ticker-data.js. Returns items list."""
    print("📡 Fetching live ticker headlines...")
    items = build_ticker_items(max_items=max_items)

    if not items:
        print("  ⚠ No live items fetched — ticker files not updated")
        return []

    updated_at = datetime.now(timezone.utc).isoformat()

    payload = {
        "updated_at": updated_at,
        "items": [
            {
                "category": item["category"],
                "label": CAT_ICONS.get(item["category"], "📰 NEWS"),
                "text": item["text"],
                "source": item["source"],
                "url": item.get("url", ""),
                "published_at": item.get("published_at", ""),
            }
            for item in items
        ],
    }

    BLOG_DIR.mkdir(parents=True, exist_ok=True)

    # Write ticker.json (for server environments)
    with open(TICKER_PATH, "w") as f:
        json.dump(payload, f, indent=2)

    # Write ticker-data.js (for file:// environments — no fetch() needed)
    js_payload = json.dumps(payload, ensure_ascii=False)
    js_content = f"/* Auto-generated by ticker_builder.py — do not edit */\nwindow.TICKER_DATA={js_payload};\n"
    with open(TICKER_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"  ✓ ticker.json + ticker-data.js: {len(items)} items saved")
    for item in items[:5]:
        cat = CAT_ICONS.get(item["category"], "📰")
        print(f"    [{cat}] {item['text'][:65]}")
    if len(items) > 5:
        print(f"    ...and {len(items)-5} more")

    return items


if __name__ == "__main__":
    build_and_save()
